services:
  mysql:
    image: mysql
    container_name: mysql-container
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  server:
    build: ./server
    container_name: server-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
  
  client:
    build: ./client
    container_name: client-container
    ports:
      - "5173:5173"
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /client/node_modules

volumes:
  mysql-data: